(define (problem problemJ)
  (:domain navigation_2)
  (:objects
x_1 y_1 x_2 y_2 x_3 y_3 x_4 y_4 x_5 y_5 x_6 y_6 x_7 y_7 x_8 y_8 x_9 y_9 x_10 y_10 - coord
kw kr kv ku kp ko kq ks kt ki kj kl kk kf kn kc ke kd km kg ka kb kh - key
dW dR dV dU dP dO dQ dS dT dI dJ dL dK dF dN dC dE dD dM dG dA dB dH - door
  )
  (:init
    (empty_hand)
    (man_pos x_10 y_1)
    (door_pos dW x_4 y_10)
    (unclear x_4 y_10)
    (unclear x_7 y_10)
    (key_pos kw x_8 y_10)
    (key_door kw dW)
    (unclear x_9 y_10)
    (key_pos kr x_10 y_10)
    (key_door kr dR)
    (succ x_1 x_2)
    (succ y_1 y_2)
    (unclear x_1 y_9)
    (unclear x_2 y_9)
    (unclear x_3 y_9)
    (unclear x_4 y_9)
    (unclear x_7 y_9)
    (unclear x_9 y_9)
    (succ x_2 x_3)
    (succ y_2 y_3)
    (key_pos kv x_1 y_8)
    (key_door kv dV)
    (unclear x_2 y_8)
    (key_pos ku x_3 y_8)
    (key_door ku dU)
    (unclear x_4 y_8)
    (key_pos kp x_6 y_8)
    (key_door kp dP)
    (unclear x_7 y_8)
    (door_pos dU x_8 y_8)
    (unclear x_8 y_8)
    (unclear x_9 y_8)
    (door_pos dV x_10 y_8)
    (unclear x_10 y_8)
    (succ x_3 x_4)
    (succ y_3 y_4)
    (unclear x_2 y_7)
    (unclear x_4 y_7)
    (unclear x_7 y_7)
    (key_pos ko x_8 y_7)
    (key_door ko dO)
    (unclear x_9 y_7)
    (key_pos kq x_10 y_7)
    (key_door kq dQ)
    (succ x_4 x_5)
    (succ y_4 y_5)
    (door_pos dO x_1 y_6)
    (unclear x_1 y_6)
    (unclear x_2 y_6)
    (door_pos dP x_3 y_6)
    (unclear x_3 y_6)
    (unclear x_4 y_6)
    (door_pos dQ x_5 y_6)
    (unclear x_5 y_6)
    (door_pos dR x_6 y_6)
    (unclear x_6 y_6)
    (unclear x_7 y_6)
    (door_pos dS x_8 y_6)
    (unclear x_8 y_6)
    (unclear x_9 y_6)
    (door_pos dT x_10 y_6)
    (unclear x_10 y_6)
    (succ x_5 x_6)
    (succ y_5 y_6)
    (key_pos ks x_1 y_5)
    (key_door ks dS)
    (unclear x_2 y_5)
    (key_pos kt x_3 y_5)
    (key_door kt dT)
    (unclear x_4 y_5)
    (key_pos ki x_5 y_5)
    (key_door ki dI)
    (key_pos kj x_6 y_5)
    (key_door kj dJ)
    (unclear x_7 y_5)
    (key_pos kl x_8 y_5)
    (key_door kl dL)
    (unclear x_9 y_5)
    (key_pos kk x_10 y_5)
    (key_door kk dK)
    (succ x_6 x_7)
    (succ y_6 y_7)
    (door_pos dI x_1 y_4)
    (unclear x_1 y_4)
    (unclear x_2 y_4)
    (door_pos dJ x_3 y_4)
    (unclear x_3 y_4)
    (unclear x_4 y_4)
    (door_pos dK x_5 y_4)
    (unclear x_5 y_4)
    (door_pos dL x_6 y_4)
    (unclear x_6 y_4)
    (unclear x_7 y_4)
    (door_pos dM x_8 y_4)
    (unclear x_8 y_4)
    (unclear x_9 y_4)
    (door_pos dN x_10 y_4)
    (unclear x_10 y_4)
    (succ x_7 x_8)
    (succ y_7 y_8)
    (key_pos kf x_1 y_3)
    (key_door kf dF)
    (unclear x_2 y_3)
    (key_pos kn x_3 y_3)
    (key_door kn dN)
    (unclear x_4 y_3)
    (key_pos kc x_5 y_3)
    (key_door kc dC)
    (unclear x_7 y_3)
    (key_pos ke x_8 y_3)
    (key_door ke dE)
    (unclear x_9 y_3)
    (key_pos kd x_10 y_3)
    (key_door kd dD)
    (succ x_8 x_9)
    (succ y_8 y_9)
    (door_pos dC x_1 y_2)
    (unclear x_1 y_2)
    (unclear x_2 y_2)
    (door_pos dD x_3 y_2)
    (unclear x_3 y_2)
    (unclear x_4 y_2)
    (door_pos dE x_5 y_2)
    (unclear x_5 y_2)
    (door_pos dF x_6 y_2)
    (unclear x_6 y_2)
    (unclear x_7 y_2)
    (door_pos dG x_8 y_2)
    (unclear x_8 y_2)
    (unclear x_9 y_2)
    (door_pos dH x_10 y_2)
    (unclear x_10 y_2)
    (succ x_9 x_10)
    (succ y_9 y_10)
    (key_pos km x_1 y_1)
    (key_door km dM)
    (door_pos dA x_2 y_1)
    (unclear x_2 y_1)
    (key_pos kg x_3 y_1)
    (key_door kg dG)
    (door_pos dB x_4 y_1)
    (unclear x_4 y_1)
    (key_pos ka x_7 y_1)
    (key_door ka dA)
    (key_pos kb x_8 y_1)
    (key_door kb dB)
    (key_pos kh x_9 y_1)
    (key_door kh dH)
  )
  (:goal
    (man_pos x_1 y_10 )
  )
)
