(define (problem problemI)
  (:domain navigation_2)
  (:objects
x_1 y_1 x_2 y_2 x_3 y_3 x_4 y_4 x_5 y_5 x_6 y_6 x_7 y_7 - coord
kc kb ka - key
dC dB dA - door
  )
  (:init
    (empty_hand)
    (man_pos x_7 y_1)
    (unclear x_4 y_7)
    (key_pos kc x_7 y_7)
    (key_door kc dC)
    (succ x_1 x_2)
    (succ y_1 y_2)
    (unclear x_4 y_6)
    (succ x_2 x_3)
    (succ y_2 y_3)
    (unclear x_4 y_5)
    (succ x_3 x_4)
    (succ y_3 y_4)
    (unclear x_1 y_4)
    (door_pos dC x_2 y_4)
    (unclear x_2 y_4)
    (unclear x_3 y_4)
    (unclear x_4 y_4)
    (unclear x_5 y_4)
    (door_pos dB x_6 y_4)
    (unclear x_6 y_4)
    (unclear x_7 y_4)
    (succ x_4 x_5)
    (succ y_4 y_5)
    (key_pos kb x_1 y_3)
    (key_door kb dB)
    (unclear x_4 y_3)
    (key_pos ka x_5 y_3)
    (key_door ka dA)
    (succ x_5 x_6)
    (succ y_5 y_6)
    (door_pos dA x_4 y_2)
    (unclear x_4 y_2)
    (succ x_6 x_7)
    (succ y_6 y_7)
    (unclear x_4 y_1)
  )
  (:goal
    (man_pos x_1 y_7 )
  )
)
